### PR TITLE
Add test for #15 issue part 2

### PR DESCRIPTION
**Pull request by lencioni**
This test case fails locally at the moment.

Addresses #15

### CODE REVIEW

**Comment by ljharb** [comment]
@nkt any chance this will be fixed soon?

**Comment by nkt** [comment]
@ljharb @lencioni I'll try to find some time to fix this on next weekend. I remember about this problem, but doesn't have enough time to fix this.

**Comment by lencioni** [comment]
I'm not sure if it is helpful for you or not, but it looks like oliviertassinari/babel-plugin-transform-react-remove-prop-types passes this test case. https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/b5adbd4af6c157b1b60b20f5d52827d47dd92813

Or perhaps the two of you could join forces?

**Comment by nkt** [comment]
This plugin deprecated. Use `babel-plugin-transform-react-remove-prop-types`.

**Pull request closed without merging**
